### ISSUE TITLE
📝 Referencing the docker survival guide

### ISSUE THREAD

**Issue by leny** [becodeorg/cli#2]
@nicolas-van has created a **docker survival guide**, currently hosted on the _private_ syllabus repo.  
It will be great to add a link to it inside the generated `docker-readme.md` from the `generate env` command.

#### TODO

- [x] @nicolas-van create a public gist with the guide
- [x] @leny reference the guide in the generated `docker-readme.md`

**Comment by nicolas-van** [comment]
Pull request waiting for approval: #4
