### ISSUE TITLE
"becode help" returns nothing

### ISSUE THREAD

**Issue by pixeline** [becodeorg/cli#8]
**Describe the bug**
typing `becode help`does not retun anything. Nor any other command.

**Screenshots**
![Capture d'écran 2019-05-17 12 41 53](https://user-images.githubusercontent.com/393415/57922926-370a4b00-78a1-11e9-8452-fa12d2f7b8e7.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.4

**Comment by leny** [comment]
Convention in UNIX is to use the flags `-h` or `--help` to get help (or `man`, but it's not easy to implement with node cli).

I prefer to stick with this behaviour, but if you think it should be good to add a `help` command printing the same text, I can, just ask.

**Comment by pixeline** [comment]
That's actually what was written in the readme file, I did not think further

__
sent via mobile, sorry for brevity and typos. °-]

**Comment by pixeline** [comment]
see https://github.com/becodeorg/cli/README.md#L40
